### ISSUE TITLE
Timezone configuration

### ISSUE THREAD

**Issue by happicamper** [jjethwa/rundeck#100]
Hello again!  Just wondering how can I adjust the docker timezone?  
I've already mounted my service with this config:  
`--mount type=bind,source=/etc/localtime,destination=/etc/localtime:ro `  
My timezone is Asia/Manila or UTC+8 but still displays UTC timezone.  
Any help is appreciated.

**Comment by jjethwa** [comment]
Hi @happicamper 

I haven't needed to do this, but maybe try adding
```
-e TZ=Asia/Manila
```

**Comment by happicamper** [comment]
@jjethwa I think my code above doesn't work for Rundeck.
Anyway, that solves my problem! :clinking_glasses:

**Comment by jjethwa** [comment]
Great news 😃
