### ISSUE TITLE
passed environment variables seem to be ignored

### ISSUE THREAD

**Issue by randyrue** [jjethwa/rundeck#103]
Bear with me if I'm missing something obvious, I'm pretty new to docker and very new to rundeck.

No matter what I do the command to launch the rundeck container seems to be ignoring -e flags passing things like EXTERNAL_SERVER_URL, RUNDECK_WITH_SSL and even RUNDECK_ADMIN_PASSWORD. I've tried both of your examples and many variations. In every case, for example,I've tried setting EXTERNAL_SERVER_URL to the both fqdn of my docker host and to its IP, the startup output tells me "Server URL set to https://localhost:4443" If I've launched docker with "-p 4443:4443" I can then load the rundeck login page on a browser on my docker host, but not from a browser on a remote machine, even though nmap on the remote machine shows a response on 4443 on the docker host. If I try "-p 4440:4440" as in your non-SSL example, from what I can tell the container is still running SSL/4443 internally and with the wrong port forwarding I can't reach it at all.

I might be having two issues, a) failing to get env variables passed to and heeded by the container, and b) exposing the container properly so it can be reached outside the docker host.

Any guidance would be greatly appreciated.

-r

**Comment by jjethwa** [comment]
Hi @randyrue 

Are you trying to front Rundeck with something like HAProxy, nginx, or similar?  If not, let's try a basic example that should hopefully work:

```
docker run -p 4440:4440 -e EXTERNAL_SERVER_URL=http://$(hostname):4440 --name rundeck -t jordan/rundeck:latest
```

That should allow you to connect to Rundeck using the hostname of the host server and port 4440 (HTTP).  Let me know if that works for you 😄

**Comment by jjethwa** [comment]
Hi @randyrue 

The certificate output can be safely ignored.  It's part of the initial startup if a keystore is not available (usually through the use of a volume).  The output at the end that says "Server URL set to..." needs to be updated, it was not updated properly when SERVER_URL was deprecated.  The latest image should fix that.

Can you provide the output of /var/log/rundeck/service.log and /var/log/rundeck/rundeck.log ?

**Comment by randyrue** [comment]
You can close this issue, after a few weeks of getting used to docker in general and your rundeck image in particular, I have a better grasp of which ENV variables your image passes along to rundeck and which I still need to manage in the rundeck-config.properties file directly.

As a way to manage the settings and content I want to be persistent, I'm mounting a local directory inside the container as /etc/rundeck, is this an acceptable way to do that? I also have a file full of other ENV variables that I'm passing with the docker run command.

**Comment by jjethwa** [comment]
Hi @randyrue 

That's great news!  Using a volume for /etc/rundeck is the best way to manage persisting the rundeck configs.  You'll probably want /var/rundeck and /var/lib/mysql for the project configs and executions as well.

**Comment by randyrue** [comment]
Thank you for your help with this, I'm clear that these are more newbie config issues than any problem with the code.

I'm connecting to an external pgsql db for project information. What other information do I need to make sure is kept outside the container?

Bonus question, is there a way to somehow use existing SSH keys that are users' home drives? Those drives are already mounted to the host machine and inside the container, I'm hoping for a way to configure RD so that when  user connects, they get their own keys by default.

**Comment by jjethwa** [comment]
Hi @randyrue   NP at all!  So you'll definitely want /etc/rundeck, /var/rundeck, /var/log/rundeck (for rundeck logs and execution logs), and /var/lib/rundeck/var/storage if you use the filestore for key storage instead of the database. Filestore is the default.

For the SSH key setup you're looking at, Rundeck's key storage is the best bet.  Check out the section at the bottom: http://rundeck.org/docs/administration/key-storage.html
