### ISSUE TITLE
Could you explain the volumes a little more

### ISSUE THREAD

**Issue by EugenMayer** [jjethwa/rundeck#105]
Thank you for your image!

I am adding a rundeck rancher catalog https://github.com/EugenMayer/docker-rancher-extra-catalogs based on your image.

I am finished so far, but i would need some more details about the volumes - most are rather self-explaining but not those 

1. /etc/rundeck 
Sounds like configuration - but how is it, arent you generating it during the bootstrap or is more in here, generated during live configuration?

2. /var/rundeck
What is stored here in general - kind of smells like "tmp"? Does this need to be a persistent ( named ) volume at all?

If you like, you can see the `docker-compose.yml` here https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/master/templates/rundeck/0/docker-compose.yml

Questions ( ENV ) are here https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/master/templates/rundeck/0/rancher-compose.yml

If you like to give feedback, just be bold anytime!

Thank you for your work providing this image

**Comment by jjethwa** [comment]
Hi @EugenMayer 

That's great!  I've been meaning to update the readme, but haven't had time recently hehe.  Happy to help with any details you need 😄 

/etc/rundeck - Contains all the base set of configurations for Rundeck and some of them are set during container initialization, but not all.  For more advanced users, they may want to persist their configuration.

/var/rundeck - Rundeck uses the file store for project configurations by default and /var/rundeck is the default location.  You can change it to use the database or change the store location if needed, but I opted for keeping things as default to a standard Rundeck install as possible.

I'll definitely check out your work and please feel free to send PRs if needed 😄

**Comment by EugenMayer** [comment]
@jjethwa i decided to fork your image - please do not take this as an offence.

I had several issues, on is the unneeded packing of myself, but also a very special docker-image layout, not support for `wait-for-it`, inconvinient variable names like `RUNDESK_PASSWORD` is actuall the DB password, not the admin password, way to big entrypoint du to all that special DB handling, hardcoded DB name, hardcoded DB username, database_url instaled of type/host/port/dbname (make wait-for-it impossible), not output to stdout/stderr of the rundeck logs, no usage of docker-compose and therefore also no usage of .env, way to complex setup with all the ENV vars in the docs ( instead of `docker-compose up` )

I understand that quiet a number of the changes above will make the image not backwards compatible, thats why i hard-forked for now with  https://github.com/EugenMayer/rundeck since i do not expect you to accept those huge PRs - it seems just to be not your way of doing this.

Again, i am really thankful for your work - i just thought that move i made was probably way to fast / far / legacy support avoided in any way

**Comment by jjethwa** [comment]
Yeah, some of the weird naming, etc were because of following the old conventions and needing to maintain support for them,  I'm pretty open to working with others, their PRs, modernisation, etc so it would have been nice to follow the natural (git) fork conventions.  Anyways, good luck! 😄

**Comment by EugenMayer** [comment]
@jjethwa maybe i did not express myself the right way - i did not PR because i though its disrespectful to PR such a huge code change without consulting with you about what to do how.

If you are interested in still get this going, i can do that anytime. But  expect a huge shift - maybe just check https://github.com/EugenMayer/rundeck before you think about that. 

For that issue here, close it anytime, you helped me a lot already!

**Comment by jjethwa** [comment]
Hi @EugenMayer 

A huge PR would be really hard to work through hehe.  I took a look at the diff and it's a lot of changes.  I'd like to take on some of your improvements, but we would need to make sure we retain backwards compatibility.  Let's see how we can work this out.  I just want to make it easier for the community to use this awesome tool 😄

**Comment by EugenMayer** [comment]
Well cherry pick whatever you like. I will at some point most probably reset the repo and split it from your fork, but for the time being, whatever you need, obviously!

I am closing this one, since the original question has been sorted out. Thank you!
