### ISSUE TITLE
Starting Supervisor.  You can safely CTRL-C and the container will continue to run with or without the -d (daemon) option

### ISSUE THREAD

**Issue by EugenMayer** [jjethwa/rundeck#106]
You should remove that message, since its not correct. If running in foreground, ctrl+c will send a HUP

**Comment by jjethwa** [comment]
Hi @EugenMayer 

How are you starting the container?  I've tested with and without the daemon flag and do not have a HUP sent when ctrl+c'ing 😛

**Comment by EugenMayer** [comment]
docker-compose of course, as i guess all will do :)

**Comment by jjethwa** [comment]
Hmm, I'd expect compose to run the container in a similar fashion, but will have to take a look.

**Comment by dandunckelman** [comment]
Confirmed.

To start the container, I run `docker-compose up rundeck` (where `rundeck` is the name of the service in my `docker-compose.yml`).

If I then press `CTRL+c`, the container immediately stops.

![image](https://user-images.githubusercontent.com/1153702/39265956-e16b078a-4885-11e8-9bef-b88911368b82.png)

I believe that's just the nature of `docker-compose` vs `docker run`.
