### ISSUE TITLE
add default web UI login info to README

### ISSUE THREAD

**Issue by jrheling** [jjethwa/rundeck#110]
Apparently it's admin:admin, which was guessable, but only after some frustrating trial and error.

**Comment by jjethwa** [comment]
Hi @jrheling 

Sorry about that.  I follow the Rundeck defaults as much as possible, so I assumed the username and password would be known.  I'll update the README on Monday 😃

**Comment by jrheling** [comment]
Thanks! Obviously it's a small thing, and likely discoverable by anybody who'd be using this.
