### ISSUE TITLE
Add RUNDECK_ADMIN_PASSWORD to secrets

### ISSUE THREAD

**Issue by djeeg** [jjethwa/rundeck#113]
Would you be open to a PR to add RUNDECK_ADMIN_PASSWORD to secrets?

I was a little confused at first, from what I can see:

Secrets documentation has:

- RUNDECK_PASSWORD
- DATABASE_ADMIN_PASSWORD

Environment documentation has:

- RUNDECK_PASSWORD
- RUNDECK_ADMIN_PASSWORD

This true?

**RUNDECK_PASSWORD** is the mysql account password for rundeck user which rundeck uses to connect to the database

**DATABASE_ADMIN_PASSWORD** is the mysql admin account that is used to create the rundeck mysql account (only seems applicable when using a remote mysql)

**RUNDECK_ADMIN_PASSWORD** is the website login password

**Comment by jjethwa** [comment]
Hi @djeeg 

Thanks for finding that discrepancy!  I forgot to add DATABASE_ADMIN_PASSWORD.  Always open for PRs.  Please send me when you have time 😄

**Comment by jjethwa** [comment]
Hi @djeeg 

I went ahead and made the changes as there is a PR for a new minor release of Rundeck and I'm sure you'd like to have this available when that gets merged 😄

**Comment by djeeg** [comment]
Tested, works as expected. Thanks!
