### ISSUE TITLE
rundeck stdout via supervisord

### ISSUE THREAD

**Issue by djeeg** [jjethwa/rundeck#114]
A few docker monitoring tools expect stdout, thoughts on outputing rundeck logs to stdout?

Would something like this be enough to enable it?
https://stackoverflow.com/questions/25195880/supervisord-redirect-process-stdout-to-console

https://github.com/jjethwa/rundeck/blob/master/content/etc/supervisor/conf.d/rundeck.conf
```
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
```

**Comment by jjethwa** [comment]
Hi @djeeg 

Thanks so much for the suggestion!  It's been on my to do list 😄 

I'll be merging a PR soon that has slightly better container shutdown handling and also will output supervisor's to stdout/stderr.  Rundeck's log would still not be output to stdout/stderr as it is still written to it's own set of log files.  I think this is a pretty good solution as the docker container logs would give you a good idea of the status of the services running inside the container.  Let me know if that is acceptable. 

The PR will be available in latest and 2.10.7 once ready.  Thanks again 😄

**Comment by jjethwa** [comment]
Hi @djeeg 

Just wanted to see if you had a chance to check out 2.10.7? Are you OK with the output?

**Comment by djeeg** [comment]
hey Jordan, just tested now, works great. thanks mate, you were so quick!
