### ISSUE TITLE
 When defining storage provides and storage type, new lines are created with each upgrade.

### ISSUE THREAD

**Issue by rsmartins78** [jjethwa/rundeck#119]
Hello,

After some tests with this image, I decided to use a separate mysql container, and set the variables "RUNDECK_STORAGE_PROVIDER" and "RUNDECK_PROJECT_STORAGE_TYPE" to db. I noticed that with each upgrade I make in the container, new lines as below are created in the rundeck-config.properties file, however in my scenario, I have a Gitlab with active CI / CD, so the file will get very large.

```ini
dataSource.url = jdbc:mysql://banco/rundeck?autoReconnect=true
dataSource.username = user
dataSource.password = pass
rundeck.storage.provider.1.type=db
rundeck.storage.provider.1.path=/
rundeck.projectsStorageType=db
rundeck.storage.provider.1.type=db
rundeck.storage.provider.1.path=/
rundeck.projectsStorageType=db
rundeck.storage.provider.1.type=db
rundeck.storage.provider.1.path=/
rundeck.projectsStorageType=db
```

**Comment by jjethwa** [comment]
Thanks for the issue, @rsmartins78   Nice catch!  I'll get it fixed 😄

**Comment by jjethwa** [comment]
Hi @rsmartins78 

Fix will be in latest and all future tagged releases.  Thanks for bringing it to my attention 👍
