### ISSUE TITLE
 Complement documentation

### ISSUE THREAD

**Issue by rsmartins78** [jjethwa/rundeck#120]
Hello, I've been testing with a mysql container separate from rundeck, and I realized that the DATABASE_URL variable should have the content similar to "jdbc:mysql://mysql/rundeck?autoReconnect=true". I had a slight problem with this case, because in my understanding, just put the IP or HOSTNAME for the connection to be made. Would you be interesting to complement README.md with an example?

**Comment by jjethwa** [comment]
Thanks @rsmartins78   I've added an example 😄
