### ISSUE TITLE
Which password is required?

### ISSUE THREAD

**Issue by lioramilbaum** [jjethwa/rundeck#121]
Dockerfile:

```
ROM jordan/rundeck

ENV RUNDECK_PASSWORD=liora \
    RUNDECK_ADMIN_PASSWORD=liora \
    DATABASE_ADMIN_PASSWORD=liora \
    KEYSTORE_PASS=liora \
    TRUSTSTORE_PASS=liora

```

```
docker exec -p 4440:4440 -e SERVER_URL=http://localhost:4440 --name rundeck -t guardium:latest
Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
sudo: 3 incorrect password attempts
```

**Comment by jjethwa** [comment]
Hi @lioramilbaum 

Is the docker exec command you are using correct?  I'm unfamiliar with guardium.  The typical command is something like:

```
sudo docker run -p 4440:4440 -e EXTERNAL_SERVER_URL=http://MY.HOSTNAME.COM:4440 --name rundeck -t jordan/rundeck:latest
```

**Comment by lioramilbaum** [comment]
@jjethwa guardium is the name of the image I have built with the Dockerfile

**Comment by lioramilbaum** [comment]
Found the root cause. sudo on my mac requires my password :-)

**Comment by jjethwa** [comment]
Hi @lioramilbaum 

It's a bit hard to tell from the output, but it looks like maybe the docker command is what is asking for privilege escalation?  So that should be the password for the account you are using that had sudo access

**Comment by jjethwa** [comment]
@lioramilbaum  simulpost lol. Glad it's working :smile:
