### ISSUE TITLE
Following Rundeck documentation

### ISSUE THREAD

**Issue by gsluka** [jjethwa/rundeck#137]
Under the "Environment Variables" section of your GitHub page, you often refer to documentation located at Rundeck's page (http://rundeck.org/docs/......). Rundeck's documentation will often provide details for RPM Install and Launcher Install. Which set of directions should we follow when configuring the rundeck container you put together, RPM or Launcher?

I'm having a hard time using ldap to sign in. Thanks for your help!

**Comment by jjethwa** [comment]
Hi @gsluka 

The container uses the Debian package.  You should just need to modify /etc/rundeck/jaas-loginmodule.conf

It should look something similar to:
```
RDpropertyfilelogin {

com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule sufficient
    debug="false"
    contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
    .
    .
    .
    cacheDurationMillis="300000"
    reportStatistics="true";

org.eclipse.jetty.jaas.spi.PropertyFileLoginModule required
    debug="false"
    file="/etc/rundeck/realm.properties"
    refreshInterval="60";
};
```

**Comment by gsluka** [comment]
Thank you!

Do I need to add LOGIN_MODULE or JAAS_CONF_FILE to my docker run command?

**Comment by jjethwa** [comment]
@gsluka   No problem 😄   There's no need to add those as they are already set to the default values in /etc/rundeck/profile

**Comment by jjethwa** [comment]
Hi @gsluka 

Any updates?

**Comment by gsluka** [comment]
Thank you for following up. I was able to login with my AD creds but was told I didn't have permission to view jobs (or do anything really). I'm trying to replicate how our current Production Rundeck is setup. I'll send additional info in the next few days.

**Comment by jjethwa** [comment]
Hi @gsluka 

You'll need to add aclpolicy files to handle permissions (probably tied to one of your AD groups) 😄

**Comment by gsluka** [comment]
@jjethwa Here is our current Rundeck setup that I am trying to replicate with my container. 

![rundeck](https://user-images.githubusercontent.com/31856008/43547601-b956220e-95a9-11e8-84ab-9c82212cd84f.PNG)
![jaas-ldap](https://user-images.githubusercontent.com/31856008/43547609-bc70f6f8-95a9-11e8-9475-576ccf8dced3.PNG)

In my container, I copied over the rundeck_users.aclpolicy from our current setup. I also added the information from our current setup into the container's jaas-loginmodule.conf file:
![container_jaas-loginmodule](https://user-images.githubusercontent.com/31856008/43548268-82835f9c-95ab-11e8-9a2e-378b9f50fd60.PNG)

After entering my docker run command and entering my credentials, the webpage resolved with an error page:
![error](https://user-images.githubusercontent.com/31856008/43548305-9651e00c-95ab-11e8-8ffe-80e6d3b8a269.PNG)

Any advice where I'm going wrong?

**Comment by gsluka** [comment]
I am logged in as Admin but am not sure how I can tell if acl policies are being loaded or not. I'm fairly new to Rundeck and still trying to learn my way around.

**Comment by gsluka** [comment]
I can confirm the rundeck_users ACL policy was loaded into the container:
![acl](https://user-images.githubusercontent.com/31856008/43792056-939a7b0a-9a45-11e8-8fc4-0e24f0392e4a.PNG)

**Comment by jjethwa** [comment]
Thanks @gsluka 

Since the aclpolicy files are loaded, it looks like the user may not be getting the rundeck-users role when authenticating.  I found this issue: https://github.com/rundeck/rundeck/issues/2781

If it is that issue, you'll need a newer version of Rundeck to get the fix.

**Comment by gsluka** [comment]
The fix was editing /var/lib/rundeck/exp/webapp/WEB-INF/web.xml on the container. Security-role needed changed to "rundeck-users". I made the file on the host, then copied the file into the container.

Once the new file was moved, I restarted the container and everything worked. Thanks for your help!
