### ISSUE TITLE
specifying volumes does not work

### ISSUE THREAD

**Issue by chenri2006** [jjethwa/rundeck#139]
Specifying volumes like this does not work:

docker run -d  \
-v `pwd`/etc/rundeck:/etc/rundeck \
-v `pwd`/var/rundeck:/var/rundeck \
-v `pwd`/var/lib/rundeck:/var/lib/rundeck \
-v `pwd`/var/lib/mysql:/var/lib/mysql \ 
-v `pwd`/var/log/rundeck:/var/log/rundeck \
-v `pwd`/opt/rundeck-plugins:/opt/rundeck-plugins \
-v `pwd`/var/lib/rundeck/logs:/var/lib/rundeck/logs \
-v `pwd`/var/lib/rundeck/var/storage:/var/lib/rundeck/var/storage \
-p 4443:4443  \ 
-e EXTERNAL_SERVER_URL=https://10.0.0.115:4443  \
-e RUNDECK_WITH_SSL=true  \
--name jordan-rundeck  \ 
-t jordan/rundeck:latest  

From the 'docker logs -f' it looks like certain subdirectories are not automatically generated:

find: '/var/lib/rundeck/cli': No such file or directory
find: '/var/lib/rundeck/bootstrap': No such file or directory

**Comment by jjethwa** [comment]
Hi @chenri2006 

As mentioned in the readme, I don't recommend using a volume for /var/lib/rundeck since it contains the webapp.  This would only be useful for someone that has extracted the webapp to the volume directory for debugging or some other weird reason 😛

**Comment by jjethwa** [comment]
Hi @chenri2006 

Any updates?

**Comment by Spencer-Dawson** [comment]
I had the same error message running your docker on unraid and your suggestion(removing /var/lib/rundeck from exposed directories) worked for me. I just assumed it was necessary because you had it listed in your VOLUME command on your Dockerfile.

**Comment by jjethwa** [comment]
Thanks for the confirmation, @Spencer-Dawson   I'll remove it in the next release as it really shouldn't be used by most users and if they really need to inject something in there, there are better ways :+1:
