### ISSUE TITLE
jaas-ldap not working in v3.0.0

### ISSUE THREAD

**Issue by moreiramarti** [jjethwa/rundeck#141]
Hi,

I'm trying to update my docker image to v3 and my ldap auth is not working anymore.
It seems that rundeck 3 uses an embedded login module or something and doesn't use my login config.

The command line I launch : 
java -Djava.security.auth.login.config=/etc/rundeck/jaas-ldap.conf -Dloginmodule.name=ldap -Drdeck.config=/etc/rundeck -Drundeck.server.configDir=/etc/rundeck -Dserver.datastore.path=/var/lib/rundeck/data/rundeck -Drundeck.server.serverDir=/var/lib/rundeck -Drdeck.projects=/var/lib/rundeck/projects -Drdeck.runlogs=/var/lib/rundeck/logs -Drundeck.config.location=/etc/rundeck/rundeck-config.properties -Djava.io.tmpdir=/tmp/rundeck -Drundeck.server.workDir=/tmp/rundeck -Dserver.http.port=4440 -Drdeck.base=/var/lib/rundeck -Xms2048m -Xmx2048m -jar /var/lib/rundeck/bootstrap/rundeck-3.0.0-20180727.war --skipinstall

Regards,
Martinho MOREIRA

**Comment by moreiramarti** [comment]
I found the issue -Djava.security.auth.login.config should be -Dloginmodule.conf.name

**Comment by jjethwa** [comment]
Thanks, @moreiramarti  I saw https://github.com/rundeck/rundeck/issues/3757 but then the PR that was linked did not include that change.  I'll get that updated now :smile:

**Comment by moreiramarti** [comment]
Thank you for your help
