### ISSUE TITLE
Configs/ Secrets can not be used from inside /etc/rundeck

### ISSUE THREAD

**Issue by danielpalstra** [jjethwa/rundeck#145]
Hi,

Docker services will fail to start when mounting docker configs/ secrets inside the `/etc/rundeck` directory. The container fails to start because of the `chown` commands used in https://github.com/jjethwa/rundeck/blob/master/content/opt/run#L17. When configs/ secrets are added the file permissions are managed by docker so they should be allright. I am opening this issue to discuss the solution so I can open a PR. 

I suggest to replace the chown commands by the following command so that files which are read only are skipped and the startup proces can continue. `find /etc/rundeck -t f -exec chown {} || true \;`

What do you think?

**Comment by jjethwa** [comment]
Hi @danielpalstra 

Thanks for reporting the issue.  The chown commands were added a long time ago to alleviate the ownership issues when using volumes.  Can you provide an example of how you are mounting secrets inside the /etc/rundeck volume?

I think we could probably limit the chown to the specific subset of rundeck configs needed as the startup process runs as root, so that find might always return the full set.

**Comment by jjethwa** [comment]
Thanks, @danielpalstra 

So the quick solution would be to set the uid, gid, and mode in the secret definition.  For example:
```
secrets:
      - source: keytab
        target: /etc/automation.keytab
        uid: '101'
        gid: '101'
        mode: 0440
```
The best way for the container to handle it would be just chown'ing the subset of directories and files it will need to touch.  That will be the safest way, what do you think?

The volumes are there for compatibility with the older versions of the container and docker, but it might be time to deprecate them.  I'll see if I can find some recommendations from the docker folks or community if it's time to do that.  Most likely, it's way past :stuck_out_tongue:

**Comment by danielpalstra** [comment]
> The best way for the container to handle it would be just chown'ing the subset of directories and files it will need to touch. That will be the safest way, what do you think?

I agree. Since docker sets the uid and gid for the mounted secres and configs the script should only touch files that are not already owned by the rundeck user. By following that approach read only files because of mounting secrets will be skipped. 

Do you want me to add a PR?

**Comment by jjethwa** [comment]
That would be great!  Thanks so much, @danielpalstra
