### ISSUE TITLE
WinRm plugin - QUESTION

### ISSUE THREAD

**Issue by RANGERBEE** [jjethwa/rundeck#147]
Anyone have success using the winRm plugin with the container ?  

 - Version 1.3.4 winRm jar file
[https://github.com/rundeck-plugins/rundeck-winrm-plugin/releases](Git REPO)

I have a Vm build running with success , the docker container is just an issue..

Thanks!

**Comment by RANGERBEE** [comment]
Hi @jjethwa ;

   Yes, install using plugins folder.  No issues with install, plugin registers and runs fine.
The issue is when connecting to hosts - the logs show empty soap strings returned....

I have a VM running old version of RD - 2.6.4-1 and using WinRm plugin 1.3.1 (running parallel) which runs fine and connects to host to execute commands perfectly.  Using all the same creds, configs on remote hosts I simply wanted to use the new RD version with the newer WinRm plugin. Met with no joy after exhaustive efforts...

I am done with WinRm - its problematic and not worth the effort short and long term. Have since moved to another solution. Believe it will be deprecated soon anyhow - for security concerns.

Thanks for the initial build - good stuff!!

**Comment by jjethwa** [comment]
Sounds good @RANGERBEE   Unfortunately, I don't have experience with the plugin, but maybe it needs a port open or something.  Glad you found something that works for you.  I'll go ahead and close this issue out.  Feel free to re-open if needed 😄
