### ISSUE TITLE
winrm plugin:  No module named requests.packages.urllib3

### ISSUE THREAD

**Issue by chiwfwigan** [jjethwa/rundeck#154]
Hi,

I've been using your Rundeck container recently and has been great - your documentation seems much better than the official rundeck container :)

I'm attempting my first Windows test, but get the following error in Rundeck:
`Traceback (most recent call last):
File "/var/lib/rundeck/libext/cache/py-winrm-plugin-1.0.7/winrm-exec.py", line 4, in <module>
import requests.packages.urllib3
ImportError: No module named requests.packages.urllib3`

Testing in the container, I see the plugin available:

/var/lib/rundeck/libext/cache/py-winrm-plugin-1.0.7

and running: python winrm-exec.py I get the same error. 

Wondering if you have seen this before?

**Comment by jjethwa** [comment]
Hi @chiwfwigan 

Thanks so much! 😄  It looks like this plugin requires a library that is not installed.  From the documentation: https://github.com/rundeck-plugins/py-winrm-plugin  Did you run: 
```
pip install pywinrm
```

**Comment by chiwfwigan** [comment]
Apologies, made some assumptions about the container (relative n00b). Lemme follow those docs and i'll get back to you!

**Comment by jjethwa** [comment]
Hi @chiwfwigan 

No problem at all!  Let me know if that works.  If it does, it looks like you'll need to run through those steps every time the container is initialized (first boot situation).  There hasn't been a use case for this yet, but I could add the ability to run your own script as part of the initialization to help automate things.

**Comment by chiwfwigan** [comment]
All good - ran the scripts and all's working as expected - now just for me to get the hang of Rundeck and WinRM! Thanks so much again for the quick help.
