### ISSUE TITLE
default credential not working

### ISSUE THREAD

**Issue by divyaimca** [jjethwa/rundeck#155]
With http url, default credential admin/admin not working. Its not showing any error, but the login is not happening.

Used : 

> sudo docker run -p 4440:4440 -e EXTERNAL_SERVER_URL=http://localhost:4440 --name rundeck -t jordan/rundeck:latest

for setup and then able to access the page with http://localhost:4440  and tried to login with admin/admin.

**Comment by kumarprd** [comment]
It works only with https not with http

**Comment by jjethwa** [comment]
Hi @kumarprd 

Have you tried using the hostname, FQDN, or IP address instead of localhost?

**Comment by jjethwa** [comment]
bump @kumarprd

**Comment by jjethwa** [comment]
Closing as no more updates
