### ISSUE TITLE
Locale support

### ISSUE THREAD

**Issue by freeseacher** [jjethwa/rundeck#156]
Please add support to install rundeck with specific locale. 
Currently if russian in logout output it will be displayd with unknown chars 

to fix it probably we should on startup script add locale-gen call and also export locale to supervisord job definitions

**Comment by jjethwa** [comment]
Thanks for reporting the issue, @freeseacher 

I can add the locale-gen command execution to the startup script.  Can you provide details about the supervisord side?  By the way, I accept PRs, so feel free to send some over if you have time :smile:

**Comment by freeseacher** [comment]
for example something like 
```
[program:rundeck]
command=/opt/supervisor/rundeck
redirect_stderr=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=LANG=ru_RU.UTF-8,LC_ALL=ru_RU.UTF-8
```

that was quick and dirty on my side to make it work for now. 
probably we should add some more logic to init mysql db correctly with good locale

**Comment by jjethwa** [comment]
Thanks for the details.  Actually, I think it would be best to set the environment variables when you start the container with docker run or in the compose file, etc.  That or override /etc/supervisor/conf.d/rundeck.conf using a volume.  I think those two options would be more in line with docker standards.  Let me know.  Thanks 😄

**Comment by jjethwa** [comment]
Hi @freeseacher 

I've added locale-get exec to the startup script.  You can add the local.gen file using the /etc/locale.gen volume  Let me know how it works for you.

**Comment by freeseacher** [comment]
> By the way, I accept PRs, so feel free to send some over if you have time 

Yep probably on weekends.

**Comment by jjethwa** [comment]
Closing due to no response.  Should work as described
