### ISSUE TITLE
3.0.16 dockerhub tag

### ISSUE THREAD

**Issue by wsoula** [jjethwa/rundeck#158]
I saw you did a 3.0.16 release and the latest tag got updated in dockerhub but there is no 3.0.16 tag in dockerhub.  Could you create that please so I can tie to a specific version instead of latest?  Thank you!  I saw in #18 you setup some automation in dockerhub, I wonder if that is no longer working or just missed the push from github.

**Comment by jjethwa** [comment]
Hi @wsoula 

I tried last week, but ran into a bug with the updated version of Docker Hub.  I can add new tags, but it only displays 25 older tags (2.x), so I cannot trigger the build.  I tried the workaround of deleting and re-creating the release in GitHub, but that did not work.  I have opened a support ticket, but it has not been updated yet 😞  Hoping it gets resolved soon so I don't have to delete the existing tags as some people might still be using the 2.x releases.

**Comment by wsoula** [comment]
For now you could just pull latest and push it as 3.0.16

**Comment by jjethwa** [comment]
Thanks @wsoula   I forgot about that ability.  Just did that 😄   Please close this issue once you've validated.  Appreciate it.

**Comment by wsoula** [comment]
Works now for me tied to tag 3.0.16
