### ISSUE TITLE
Lost+found in /etc/rundeck

### ISSUE THREAD

**Issue by h4wkmoon** [jjethwa/rundeck#159]
Hi, 
I think the line mentioned below will prevent the image to work properly when /etc/rundeck is a volume with a "lost+found" folder.

https://github.com/jjethwa/rundeck/blob/7e0da10a68b6e366d53cf386ba28832a83bba351/content/opt/run#L93

**Comment by jjethwa** [comment]
Hi @h4wkmoon 

As a failsafe, if anything is found, no defaults will be copied over.  You're correct that lost+found is safe to ignore.  Would you like to submit a PR?

**Comment by rdehouss** [comment]
This ticket can be closed, right?

**Comment by jjethwa** [comment]
Thanks for the reminder, @rdehouss
