### ISSUE TITLE
Speed up rundeck

### ISSUE THREAD

**Issue by jolbax** [jjethwa/rundeck#16]
Hi @jjethwa 
This is actually not an issue, rather a question.
Is there a possibility to speed up things? I really like your container. I'm running it for testing purposes on a VM with 4 GB of mem and 4 cores.
I already set the "/etc/rundeck/profile" settings to the double. 
But the WebGUI is still kind of slow. 
The container does not use all the VM resources 
```
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O               BLOCK I/O
rundeck             0.98%               669.4 MB / 3.968 GB   16.87%              685.5 kB / 975.8 kB   24.58 kB / 221.2 kB
```

Do you have an idea?
Are you also using the container for production purposes?

**Comment by jjethwa** [comment]
Hi @jolbax 

You could try tuning the JVM a bit more in /etc/rundeck/profile a bit more.  I'm using the default JVM settings and don't notice any difference between the container and standard install and that is with 10 projects and hundreds of executions everyday 🙂

**Comment by jjethwa** [comment]
Hi @jolbax 

The latest version of Rundeck has some performance tweaks.  Please check it out and close this issue :)

**Comment by jolbax** [comment]
@jjethwa 
Thanks!

**Comment by jolbax** [comment]
@jjethwa 
It is much faster!
