### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by moreiramarti** [jjethwa/rundeck#161]
Hello,

I just upgrade from rundeck 3.0.11 to 3.0.19 and when I try to log in, I got this error : 

Refused to send form data to 'http://rundeck.eileo-local.org/' because it violates the following Content Security Policy directive: "form-action 'self'".

Any ideas ?

I'm using nginx in front of rundeck with ssl offload

Thank you

**Comment by jjethwa** [comment]
Hi @moreiramarti 

Please see: https://github.com/rundeck/rundeck/issues/4417

Let me know if setting the appropriate header resolves the issue for you :smile:

**Comment by moreiramarti** [comment]
Thank you it works now
