### ISSUE TITLE
User Name and Password

### ISSUE THREAD

**Issue by vchauha6** [jjethwa/rundeck#162]
hi there,
I started the server both http and https bothways. username : admin and password:admin does not work. Is there any other option ?

**Comment by jjethwa** [comment]
Hi @vchauha6 

admin is the default username and password: https://github.com/jjethwa/rundeck/blob/master/content/opt/rundeck-defaults/realm.properties#L25

Are you using a volume for /etc/rundeck?  Have you modified the real.properties?  What is the docker run command you are using?

**Comment by jjethwa** [comment]
Closing as no more updates
