### ISSUE TITLE
rundeck-config.properties grows after each restart

### ISSUE THREAD

**Issue by pschmitt** [jjethwa/rundeck#17]
Hi,

I like to destroy my containers each and every time they are restarted (I use mapped volumes to ensure persistence). This has a side effect. Each time the new container is started the `rundeck-config.properties` file grows.
Is there any reason to append the MySQL config when the container starts? The other config items get updated via sed.

Affected lines: https://github.com/jjethwa/rundeck/blob/master/content/opt/run#L105-L106

Example rundeck-config.properties after a few restarts: 

```
#loglevel.default is the default log level for jobs: ERROR,WARN,INFO,VERBOSE,DEBUG
loglevel.default=INFO
rdeck.base=/var/lib/rundeck

#rss.enabled if set to true enables RSS feeds that are public (non-authenticated)
rss.enabled=false
# change hostname here
grails.serverURL=https://mydomain.com:443

dataSource.url = jdbc:mysql://localhost/rundeckdb?autoReconnect=true
dataSource.username = rundeck
dataSource.password = myDumbPASSWORD
dataSource.username = rundeck
dataSource.password = myDumbPASSWORD
dataSource.username = rundeck
dataSource.password = myDumbPASSWORD
dataSource.username = rundeck
dataSource.password = myDumbPASSWORD
dataSource.username = rundeck
dataSource.password = myDumbPASSWORD
dataSource.username = rundeck
dataSource.password = myDumbPASSWORD
dataSource.username = rundeck
dataSource.password = myDumbPASSWORD
dataSource.username = rundeck
dataSource.password = myDumbPASSWORD
dataSource.username = rundeck
dataSource.password = myDumbPASSWORD
dataSource.username = rundeck
dataSource.password = myDumbPASSWORD
```

**Comment by jjethwa** [comment]
Hi @pschmitt 

Thanks for reporting the issue.  I had meant to fix it but forgot about it as I moved to using the groovy config file for my instances.  I'll get this fixed by today :)

**Comment by jjethwa** [comment]
Hi @pschmitt 

This commit should take of that issue: https://github.com/jjethwa/rundeck/commit/03d85c614452ca10c169d7afd99792e14fe875c0

The new build is available via Docker Hub.

Please confirm that it works as expected for you and close this ticket.  Thanks :)

**Comment by pschmitt** [comment]
I tested and it works as expected. Good job.
