### ISSUE TITLE
Versioned Tags on Docker Hub

### ISSUE THREAD

**Issue by SQiShER** [jjethwa/rundeck#18]
First of all: Thanks for this image! It works very well for us.

I just wanted to ask, if you ever considered releasing versioned tags on Docker Hub? I generally refrain from using the `latest` tag for more important pieces of my infrastructure, so I don't get surprised by unexpected version bumps. Currently I work around this by having a fork of your repository, creating tags for the versions I'm using and have my CI build and push a tagged version of the image to our internal registry. Not really a big deal, but still some extra effort I'd like to avoid.

Just wanted to ask if you are open to the idea of specific version tags. If the answer is yes, I'd be happy to help.

**Comment by jjethwa** [comment]
Hi @SQiShER 

Thanks so much and yes, I am open to it and should have been doing it.  Help is always appreciated🙂

**Comment by jjethwa** [comment]
Hi @SQiShER 

Just tagged in git and setup the tag build on Docker Hub for 2.6.6.  Let me know how it looks.  I'll keep it up for future releases🙂

**Comment by SQiShER** [comment]
Hey @jjethwa, woohoo, awesome! Thanks a lot! Works like a charm! 🎉
