### ISSUE TITLE
Plugins not host-mountable

### ISSUE THREAD

**Issue by flypenguin** [jjethwa/rundeck#19]
Currently the plugin directory is `$RUNDECK_DIR/libext`, and is pre-filled with a bunch of default ones. Adding plugins is "copy plugin file into this directory" according to the official documentation. Unfortunately in a dockerized deployment this directory is in the container, and when I host-mount it, it will be empty - so the default plugins will not be available.

Can you fix this somehow? Rename and copy on startup for example, or symlink in from somewhere else (if possible)?

**Comment by jjethwa** [comment]
Hi @flypenguin 

What plugins were you looking to add? :)

**Comment by flypenguin** [comment]
amazon ec2 for example ;) . maybe more, don't know yet.

**Comment by jjethwa** [comment]
Hi @flypenguin 

Changes are in the latest container.  Just drop the plugin jars you want to the /opt/rundeck-plugins directory and they will be copied over at container start up :)

**Comment by flypenguin** [comment]
awesome :) . thanks for the super-quick fix, I'll test (hopefully) today

**Comment by jjethwa** [comment]
Hi @flypenguin 

Tagged the 2.6.7 release which contains the changes as well.  Hopefully it's working as expected :)

**Comment by flypenguin** [comment]
seens to work like a charm btw :) . thanks a lot!
