### ISSUE TITLE
MariaDB character set issue

### ISSUE THREAD

**Issue by DeLoWaN** [jjethwa/rundeck#204]
Hi, when upgrading from Rundeck 3.3.9 to 3.4.8, I stumble upon this error:

```
[2021-12-15T16:05:33,462] ERROR boot.SpringApplication - Application run failed
liquibase.exception.MigrationFailedException: Migration failed for change set core/ConstraintsIndexesKeys.groovy::3.4.0-36::rundeckuser (generated):
     Reason: liquibase.exception.DatabaseException: (conn=36) Index column size too large. The maximum column size is 767 bytes [Failed SQL: (1709) CREATE INDEX EXEC_IDX_1 ON rundeckdb.execution(id, date_completed, project)]
```

Actually [like this error](https://github.com/rundeck/rundeck/issues/2721).

I managed to fix it my manually converting all tables to charset `utf8` instead of `utf8mb4`.

I was wondering if it's linked to this docker image or Rundeck itself.

**Comment by jjethwa** [comment]
Hi @DeLoWaN 

Thanks for the issue.  The container does not set the encoding for the database.  I think the issue you ran into stems from this: https://docs.rundeck.com/docs/upgrading/upgrading-to-rundeck-3.4.html#package-repositories

I'll add the changes to the default config just in case

**Comment by jjethwa** [comment]
Hi @DeLoWaN 

Just added the recommended setting and it'll go out with a new release of the container (when Rundeck releases 3.4.9 or higher is available).  I'll go ahead and close this ticket, but feel free to open it up if needed.
