### ISSUE TITLE
Rundeck service.log to stdout

### ISSUE THREAD

**Issue by venkatashreevaatsava** [jjethwa/rundeck#209]
Hi Team,

We are currently running rundeck in EKS and running successfully. We could not read logs using kubectl logs -f <rundeck pod name> and logs are of docker logs not rundeck service.log.. currently we are SSH in to the pod and verifying logs. We need to see logs from rundeck using  kubectl logs -f <rundeck pod name> by default.

Kindly help

**Comment by jjethwa** [comment]
Hi @venkatashreevaatsava 

That's the default behaviour as set up in log4j2 (reference: https://docs.rundeck.com/docs/administration/maintenance/logs.html#streaming-log-plugins ).  As soon as the logging service starts up, STDOUT is redirected to the service.log.  You could take a look at your log4j2.properties and modify it, but that could output a lot of data to your docker logs, so I wouldn't really recommend it  😄

**Comment by venkatashreevaatsava** [comment]
can you please explain what modification required in log4j.properties

**Comment by jjethwa** [comment]
Hey @venkatashreevaatsava 

Sorry, I'm not an expert in log4j2.  I really don't recommend doing it as you're going to put 100MBs or GBs in your docker logs.  Most people would export the logs to something like splunk.

**Comment by jjethwa** [comment]
Closing as no more updates

**Comment by jjethwa** [comment]
Closing as no more updates
