### ISSUE TITLE
Groovy Plugin Support

### ISSUE THREAD

**Issue by stagrlee** [jjethwa/rundeck#21]
Was trying to load the PagerDutyNotification.groovy plugin into the rundeck container, but it does not get loaded.

https://github.com/rundeck-plugins/pagerduty-notification

Currently the container loads up ZIP and JAR plugins off the /opt/rundeck-plugins mounted volume but skips plugins implemented in groovy.

**Comment by jjethwa** [comment]
Hi @stagrlee 

This commit should take care of it: https://github.com/jjethwa/rundeck/commit/268fa1004beca686f274e2049c314cb230924c0f

The fix will be in the latest container (being built right now on Docker Hub) and will make it into the next tagged release.

Please close this issue after you've validated it.  Thanks :)
