### ISSUE TITLE
Consider an Oauth capable variant

### ISSUE THREAD

**Issue by donaldguy** [jjethwa/rundeck#31]
I prototyped out in my work and reduced to this gist:
https://gist.github.com/donaldguy/eaa99fb0d1f17c0576255c3cf3ffc7ea

The runtime `cp`s are necessary cause of the non-empty `/etc/rundeck` and `/var/lib/rundeck/` volumes, but starting from scratch you could get away without them.

**Comment by jjethwa** [comment]
Hi @donaldguy 

Thanks so much!  I'll take a look into it :)

**Comment by jjethwa** [comment]
Hi @donaldguy 

Sorry, I've been swamped for the past few days.  I'll definitely look into this as soon as I can :)

**Comment by amontalban** [comment]
Hi @jjethwa,

Have you tried to implement this? I'm trying to enable oauth in Rundeck so if you want I can try to solve this issue.

Please let me know.

Thanks!

**Comment by jjethwa** [comment]
Hi @amontalban 
CC: @donaldguy 

Sorry, I have not had time to work on anything yet.  The gist from @donaldguy has everything that needs to be implemented to get OAuth working.  I think the integration work would be getting the module built then gating (If OAuth enabled then...) the Rundeck config part.  Any help would be appreciated as I'm still underwater at the day job :)
