### ISSUE TITLE
Document /var/lib/rundeck/logs as a volume

### ISSUE THREAD

**Issue by sixcorners** [jjethwa/rundeck#35]
Shouldn't /var/lib/rundeck/logs be documented as a volume? If the stuff in that directory isn't saved it seems that the logs for each job invocation are lost when a new container is created.

While we are at it could /var/lib/rundeck/var/storage get the same treatment?

**Comment by jjethwa** [comment]
HI @sixcorners 

Yes, you're correct.  I'll go ahead and add those two into the Docker file and readme right now.  Thanks for reporting the issue :)

**Comment by jjethwa** [comment]
Hi @sixcorners 

https://github.com/jjethwa/rundeck/commit/bbf8132c8b18efdf7672bab40a84cf7dab068c70

Changes will be available in the latest container (building now on Docker Hub) and will be in all new releases going forward.  Thanks for reporting the issue.  Please close this issue once you're validated on your end :)

**Comment by sixcorners** [comment]
I'm not sure there is much I can validate. I made them volumes when I deployed it so they should still be volumes after this change. I wonder if this affects people who don't have these set to be volumes negatively.

**Comment by jjethwa** [comment]
Hi @sixcorners 

No, it won't cause issues.  If a user does not use the volume, the default behaviour will continue to work.  Thanks again :)
