### ISSUE TITLE
Reduce container size by ~107Mb

### ISSUE THREAD

**Issue by amontalban** [jjethwa/rundeck#38]
Hi @jjethwa,

This issue is to reduce container size by ~107Mb by running curl commands for the Rundeck deb packages in one step and doing some word-wrap syntax tidy up.

Also I removed some ENV variables that are already default in /opt/run.

Let me know what do you think.

Thanks!

**Comment by jjethwa** [comment]
Thanks again @amontalban 

Really appreciate it!  Merging now :)
