### ISSUE TITLE
Rundeck should wait until MySQL is ready when using external server

### ISSUE THREAD

**Issue by amontalban** [jjethwa/rundeck#40]
Hi @jjethwa,

I swear this is the last issue/PR I do for today until I focus on #31 :).

This fix is for allowing Rundeck to wait until MySQL is ready for accepting connections, in my case I use a docker-compose with `percona/percona-server` container as DB server and it takes some seconds to come up when launching it for first time. So this adds the `wait-for-it` script that ensures there is connectivity to needed port before launching Rundeck.

The timeout time is optional and defaults to 2 minutes.

Thanks for all the merges!

**Comment by jjethwa** [comment]
HI @amontalban 

lol np with the number if issues and PRs.  I really appreciate it.

**Comment by jjethwa** [comment]
Hi @amontalban 

Had a small issue with Docker Hub not being able to push the image that it built, but it got resolved.  Latest container has it :)
