### ISSUE TITLE
Error in start script updating MySQL password

### ISSUE THREAD

**Issue by ricktrintech** [jjethwa/rundeck#47]
Getting error below when starting up:
ERROR 1054 (42S22) at line 1: Unknown column 'password' in 'field list'

Looks like MySQL 5.7 password field has been changed from 'password' to 'authentication_string', run script needs to be updated.

Ref: http://stackoverflow.com/questions/30692812/mysql-user-db-does-not-have-password-columns-installing-mysql-on-osx

**Comment by jjethwa** [comment]
Hi @ricktrintech 

I'm currently away from my computer for another week or so, but in the meantime, are you using the included MySQL db or an external instance?

**Comment by ricktrintech** [comment]
I'm using the included MySQL

**Comment by jjethwa** [comment]
Hi @ricktrintech 

Sorry for the delay, I'm back from vacation :)  I pulled the latest rundeck container from Docker Hub and it is using MySQL 5.5.52-0+deb8u1  I ran some tests and could not reproduce the issue with the included version (which is the current version recommended for jessie: https://packages.debian.org/jessie/mysql-server )

Do you mind pulling the latest container and trying again?

**Comment by Jameshofo** [comment]
This appears related to my issue, I tried this docker image and was not able to login to the UI. I'll try pulling the latest to see if it works.

**Comment by jjethwa** [comment]
Thanks @Jameshofo 

Looking forward to your results :)

**Comment by LoungeFlyZ** [comment]
I think i am hitting the same issue.  Fire up the latest image and specify a password.  Cant login with rundeck and pass@word1.  Here is the stdout from the container:

`docker run -p 4440:4440 -e SERVER_URL=http://localhost:4440 -e RUNDECK_PASSWORD=pass@word1 --name rundeck -t jordan/rundeck:latest
=>Initializing rundeck - This may take a few minutes
=>Generating rundeck key
Generating public/private rsa key pair.
Your identification has been saved in /var/lib/rundeck/.ssh/id_rsa.
Your public key has been saved in /var/lib/rundeck/.ssh/id_rsa.pub.
The key fingerprint is:
0d:56:87:9b:24:3e:6e:e8:3f:63:c0:3a:c3:0f:0a:b4 rundeck@7a27f4540741
The key's randomart image is:
+---[RSA 4096]----+
|          ...    |
|        ..o.     |
|       .oo o     |
|       .ooo      |
| .   . oS..      |
|. .   + o        |
|.E ..o o         |
| . .=.. +        |
|  .  +.o.o       |
+-----------------+
=>/etc/rundeck check OK
=>Generating ssl cert
=>Initializing local MySQL...
[ ok ] Starting MySQL database server: mysqld ..
[info] Checking for tables which need an upgrade, are corrupt or were
not closed cleanly..
[ ok ] Stopping MySQL database server: mysqld.




===================================================================
MySQL user 'root' has no password but only allows local connections
MySQL user 'rundeck' password set to pass@word1
Rundeck project storage type set to file
Rundeck Storage provider set to file
Rundeck public key:
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCncwsWn0giKNawkx9gq+pAWqIc6w4WQ/4vnyAQqWOY3+9Yj1ot4vvKjezuxEzcGpetZTxovyJa/vOtH1rySgayaW5vfUNRgLKvxVfAw8/DxpEvu8/y33KeA6i/j7kqp1lUq87xYTgtchKsX96EiCuKpCvhOxCuHH5p6siy9XibFjmdxsBFrsoEJ7sMgVrK5YUJixXfn0eHKLg8XARZET4daoJHuj/zdxemoediFScHr0W2Fy+LVJRvIiT9Sgp7uByZVKEDQyviTMqZgvY2Bo2KLxC3EHsxrtPP7JmOIJ/MOdDxvjR9Ize/jxHtvCXlpKAUTrpQwMkpejChXYcn8Xy2SkC84VoZls0Tzs2N8S43Z21yguq2qYO7xiGoSI2VNP13/V9kr49hXL/IFZt3FqECD35wr7fz5YpL3TwhqIzm4cRCdv4XdOwMFGyksDFQ8FhRvCGKiTBtZLSMJKOnEB+D46F9NDhz2TgSraMpAdZrspa9lsrDthNRytrzEmVLZV5c0vk1AS3pwF8ADtA0gSnTwMspslpGC/bpAh4c4qBAHule7GtSVb5aOeXlG+1dNxZ7pT4tHYN3SCiCNqfw3MnZ4Bi6Bhn8sdeiBKPK0tRGjDaQgUhSEFAWhU6ZkBkHYxOyrd8Ns1CA9mEb8h9cmWX5awT1iHw4RpQDuUi1tp2KmQ== rundeck@7a27f4540741
Server URL set to http://localhost:4440
===================================================================
Starting Supervisor.  You can safely CTRL-C and the container will continue to run with or without the -d (daemon) option`

**Comment by jjethwa** [comment]
Hi @LoungeFlyZ 

Do you mean that you are unable to log in to the UI?  If so, you need to use the RUNDECK_ADMIN_PASSWORD var

**Comment by LoungeFlyZ** [comment]
@jjethwa thx! wow i cant believe i missed that.  thx for the pointer.

**Comment by jjethwa** [comment]
@LoungeFlyZ 

That's great news!  Glad it's working 😄
