### ISSUE TITLE
Rundeck tries to connect to docker host when using external DB

### ISSUE THREAD

**Issue by robertobado** [jjethwa/rundeck#52]
Hi all. Before we talk about any issue, congratulations for the great work with this image!

I can run it with embedded database locally and it worked great.

When I try to use an external database in my production environment, rundeck seems to keep trying to connect to docker host as it's mysql. I am opening this issue with the true hope I am actually missing something on my side, but I already exhausted my creativity trying to solve this :/

I am running this image using a docker-compose, with the following environment variables defined:

 environment:
       - SERVER_URL=http://10.74.0.10:4440
       - DATABASE_URL=jdbc:mysql://10.96.10.190/super_rundeck?autoReconnect=true
       - RUNDECK_PASSWORD=123Rundeck$$
       - RUNDECK_STORAGE_PROVIDER=db
       - RUNDECK_PROJECT_STORAGE_TYPE=db
       - NO_LOCAL_MYSQL=true

When I launch the service, I can confirm the variable is properly set inside container:

root@ceda805208ea:/var/log/rundeck# echo $DATABASE_URL
jdbc:mysql://10.96.10.190/super_rundeck?autoReconnect=true

And even in rundeck config file:

root@ceda805208ea:/var/log/rundeck# grep dataSource.url /etc/rundeck/rundeck-config.properties
dataSource.url = jdbc:mysql://10.96.10.190/super_rundeck?autoReconnect=true

But service actually fails to start, and /var/log/rundeck/service.log is filled with database connection errors like below:

java.sql.SQLException: Access denied for user 'rundeck'@'10.74.0.12' (using password: YES)
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.

10.74.0.12 is actually my docker host primary IP address. Why is it trying to connect there? I searched config but could not find any reference for that ip address there.

I also noted that if I change database url with something with an invalid syntax (like "jdbc:myyyyyyysql://...." it fails with a bad configuration error, indicating that the property seems to be read at some point, but I also noted that if I change it to a valid syntax but a random IP address which goes nowhere (like "jdbc:mysql://10.96.111.111/....") it also tries to connect to 10.74.0.12

Any help is appreciated. Thanks in advance.

**Comment by jjethwa** [comment]
HI @robertobado 

Thanks for your kind words 😄 

This is a strange issue.  Are you able to connect to the MySQL database from within the Rundeck container using the CLI client?

```
mysql -u rundeck-p -h 10.96.10.190
```

**Comment by robertobado** [comment]
Hi @jjethwa, sorry for the delay.

Yes, I am able to connect via mysql client:

root@24a2620025f2:/# mysql -h 10.96.10.190 -u rundeck -p
Enter password:
Welcome to the MySQL monitor.

:/

**Comment by jjethwa** [comment]
Hi @robertobado 

According to https://dev.mysql.com/doc/refman/5.7/en/problems-connecting.html , it looks like you can get the wrong IP listed if MYSQL is unable to verify the client's address.  In this case, when connecting via  JDBC from the Docker container, MYSQL can only verify the host's IP.  There are a couple things to try in link above.  Another idea might be granting the rundeck user permission from all hosts or a subset of hosts:

All hosts example:
```
grant ALL on rundeck.* to 'rundeck'@'%' identified by '123Rundeck$$';
```

**Comment by robertobado** [comment]
Hi @jjethwa, thanks for the reply.

I was checking with my ops team and credentials used by rundeck are already open to be accessible  by any host. It also seems a little suspicious that I can connect from container mysql command line client but not from the application, assuming the problem is host restriction. 

Do you see any special reason why the application would be handled differently?

Thank you in advance once more.

**Comment by jjethwa** [comment]
Hi @robertobado 

Since you confirmed connectivity using the client from within the container itself, I think it might be something to do with the JDBC Connector.  I wonder if it would help specifying some properties like setting the mode to TCP?  See: https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html

Sorry, I have more experience with MySQL containers 😢

**Comment by robertobado** [comment]
After moving rundeck to a different host and using latest version, I was able to connect to external database properly. Thanks for the attention @jjethwa.

**Comment by jjethwa** [comment]
Great news! 😃

**Comment by bn8595** [comment]
what is the solution to this issue, I am also having same issue in my new environment. in my case when I access mysql from rudeck container manually using mysql -r rundeck -h IP -p command I can access. but when I try to access rundeck url from outside I keep on getting below error.
HTTP ERROR: 503
Problem accessing /. Reason:

    Service Unavailable
Powered by Jetty://

**Comment by jjethwa** [comment]
Hi @bn8595 

Is there anything in your service or rundeck log that indicates what is wrong?

**Comment by bn8595** [comment]
@jjethwa below are the config details.
cat service.log
2018-07-31 12:49:26.714:WARN:oejuc.AbstractLifeCycle:main: FAILED org.eclipse.jetty.server.Server@502a4156: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:264)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at org.eclipse.jetty.server.Server.doStart(Server.java:303)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:128)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:81)
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:264)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at org.eclipse.jetty.server.Server.doStart(Server.java:303)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:128)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:81)
WARNING: HTTPS is not enabled, specify -Drundeck.ssl.config=/var/lib/rundeck/server/config/ssl.properties to enable.
2018-07-31 12:49:30.206:INFO:oejs.Server:main: jetty-9.0.7.v20131107
2018-07-31 12:49:33.116:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
2018-07-31 12:49:34.801:INFO:/:main: Initializing Spring root WebApplicationContext
WARNING: HTTPS is not enabled, specify -Drundeck.ssl.config=/var/lib/rundeck/server/config/ssl.properties to enable.
2018-07-31 12:49:56.216:INFO:oejs.Server:main: jetty-9.0.7.v20131107
2018-07-31 12:49:59.078:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
2018-07-31 12:50:00.663:INFO:/:main: Initializing Spring root WebApplicationContext
root@9f06b525e139:/var/log/rundeck#

root@9f06b525e139:/var/log/rundeck# cat /etc/rundeck/rundeck-config.properties
#loglevel.default is the default log level for jobs: ERROR,WARN,INFO,VERBOSE,DEBUG
loglevel.default=INFO
rdeck.base=/var/lib/rundeck
NO_LOCAL_MYSQL=true
SKIP_DATABASE_SETUP=true
#rss.enabled if set to true enables RSS feeds that are public (non-authenticated)
rss.enabled=false
# change hostname here
grails.serverURL=http://172.18.1.5:4440
dataSource.dbCreate = update
dataSource.url = jdbc:mysql://mysqlhost/rundeckdb?autoReconnect=true
dataSource.username = rundeck
dataSource.password = FZwwQzV2TpGRDeK
#dataSource.driverClassName=com.mysql.jdbc.Driver
root@9f06b525e139:/var/log/rundeck#

from both the containers I can telnet. From rundeck container I can login to mysql db using rundeck user. 
I am using below images
root@sutest03:~# docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
jordan/rundeck        latest              7651650096ec        13 days ago         959MB
portainer/portainer   latest              7afb7abcfe5f        5 weeks ago         57MB
cytopia/mysql-5.7     latest              ac5e1664fe95        5 months ago        1.37GB
root@sutest03:~#

and continue to receive below error.
HTTP ERROR: 503
Problem accessing /. Reason:
Service Unavailable
Powered by Jetty://

**Comment by bn8595** [comment]
@jjethwa Thanks for the help. I changed the port and it worked. at the time of creation I used 4441:4440.

**Comment by jjethwa** [comment]
Great news, @bn8595 😄
