### ISSUE TITLE
Provide guidance on use behind corporate proxies

### ISSUE THREAD

**Issue by cosmocracy** [jjethwa/rundeck#54]
I found that much trial-and-error was needed to get the Rundeck image to work as desired when there is a corporate proxy between Rundeck and the internet.  (This was primarily needed for access to GitHub.com for the SCM plugin.)

If you take a look at issue https://github.com/rundeck/rundeck/issues/1777 you can see some commentary related to the work needed to pass through DNS as well as the proxy variables.  I know this is not "rundeck-specific" but sometimes providing guidance like this goes a long way toward boosting adoption and saving your admins/users headaches.

Perhaps an extra section in the README? Or a dedicated Wiki page (linked to from the README)?

**Comment by jjethwa** [comment]
Thanks @cosmocracy 

That's a great idea and thanks for the info  Would you like to send a PR with the README update since you did all of the legwork? 😃

**Comment by cosmocracy** [comment]
Can do!

**Comment by vipulagarwal** [comment]
I ran into this problem and resolved it using your method. I have created a [patch](https://github.com/vipulagarwal/rundeck/commit/45acb8f1d6a0162ac2c2ebdf0ec086ef12155af1) for the readme. Please let me know if it is OK to submit a pull request.

**Comment by jjethwa** [comment]
Hi @vipulagarwal 

Thanks so much!  Please submit the PR at your earliest convenience 😄

**Comment by vipulagarwal** [comment]
Np @jjethwa - pull request [91](https://github.com/jjethwa/rundeck/pull/91) opened
