### ISSUE TITLE
Can't add external plugins on Windows

### ISSUE THREAD

**Issue by dmitry-reshetnik** [jjethwa/rundeck#57]
docker run -p 4440:4440 -e SERVER_URL=http://<IP>:4440 -t jordan/rundeck:latest -v "//D/temp/plugins:/opt/rundeck-plugins"

d:\temp\plugins contains plugins JAR files

After launching the container Plugins List doesn't contain any of added plugin.
do I need to configure anything?

And how to update <node> list?

**Comment by jjethwa** [comment]
Hi @dmitry-reshetnik 

I'm not familiar with running Docker on Windows.  Have you followed the instructions for sharing the drive?

https://docs.docker.com/docker-for-windows/#shared-drives

Also, please make sure you are running the latest version of the container.

**Comment by dmitry-reshetnik** [comment]
trying to do the same on Ubuntu using the latest version
-v /home/user/plugins:/opt/rundeck-plugins
my folder contains plugin files. after execution /opt/rundeck-plugins/ folder is empty..

the same with  '/var/lib/rundeck/.ssh'

**Comment by dmitry-reshetnik** [comment]
Incorrect 'docker run' arguments

**Comment by jjethwa** [comment]
Thanks for the update, @dmitry-reshetnik   Glad it's working 👍
