### ISSUE TITLE
mysqld does not start when using Volumes

### ISSUE THREAD

**Issue by bscott** [jjethwa/rundeck#6]
mysqld does not start when using Volumes, also should allow to link a mysql container. 

Volumes:
```
/srv/docker/rundeck/mysql:/var/lib/mysql
```

Log:
```
8/3/2015 9:10:49 PMInitializing rundeck - This may take a few minutes
8/3/2015 9:10:49 PMGenerating rundeck key
Invalid Date Invalid DateGenerating public/private rsa key pair.
Invalid Date Invalid DateCreated directory '/var/lib/rundeck/.ssh'.
Invalid Date Invalid DateYour identification has been saved in /var/lib/rundeck/.ssh/id_rsa.
8/3/2015 9:10:49 PMYour public key has been saved in /var/lib/rundeck/.ssh/id_rsa.pub.
Invalid Date Invalid DateThe key fingerprint is:
Invalid Date Invalid Date58:fd:05:ca:26:0f:ff:ea:57:02:a6:ca:56:17:f8:3c rundeck@e19a616b64e8
Invalid Date Invalid DateThe key's randomart image is:
Invalid Date Invalid Date+--[ RSA 2048]----+
Invalid Date Invalid Date|            .    |
Invalid Date Invalid Date|         o . .   |
8/3/2015 9:10:49 PM|        +.=   .  |
Invalid Date Invalid Date|       o.*+. .   |
Invalid Date Invalid Date|      . S=oo.    |
Invalid Date Invalid Date|        o E.. .  |
Invalid Date Invalid Date|     . o . ..o   |
Invalid Date Invalid Date|      +    ..    |
8/3/2015 9:10:49 PM|     .   .o.     |
Invalid Date Invalid Date+-----------------+
8/3/2015 9:11:00 PMInitializing rundeck - This may take a few minutes
Invalid Date Invalid DateGenerating rundeck key
8/3/2015 9:11:00 PMGenerating public/private rsa key pair.
8/3/2015 9:11:00 PMCreated directory '/var/lib/rundeck/.ssh'.
Invalid Date Invalid DateYour identification has been saved in /var/lib/rundeck/.ssh/id_rsa.
Invalid Date Invalid DateYour public key has been saved in /var/lib/rundeck/.ssh/id_rsa.pub.
8/3/2015 9:11:00 PMThe key fingerprint is:
8/3/2015 9:11:00 PM58:fd:05:ca:26:0f:ff:ea:57:02:a6:ca:56:17:f8:3c rundeck@e19a616b64e8
Invalid Date Invalid DateThe key's randomart image is:
Invalid Date Invalid Date+--[ RSA 2048]----+
8/3/2015 9:11:00 PM|            .    |
8/3/2015 9:11:00 PM|         o . .   |
Invalid Date Invalid Date|        +.=   .  |
8/3/2015 9:11:00 PM|       o.*+. .   |
8/3/2015 9:11:00 PM|      . S=oo.    |
Invalid Date Invalid Date|        o E.. .  |
8/3/2015 9:11:00 PM|     . o . ..o   |
8/3/2015 9:11:00 PM|      +    ..    |
8/3/2015 9:11:00 PM|     .   .o.     |
8/3/2015 9:11:00 PM+-----------------+
8/3/2015 9:11:04 PM[....] Starting MySQL database server: mysqld . . . . . . . . . . . . . .[?25l7[1G[[31mFAIL[39;49m8[?12l[?25h [31mfailed![39;49m
```

**Comment by jjethwa** [comment]
Thanks for opening up the issue, @bscott 

The init tries to chown /var/lib/mysql to make sure it can be used by the mysql user.   Do you see the permissions changing on the volume after trying to start the container? 

Is there existing mysql database files in the volume directory?   If not, it might be best to start the container without the volume then copy over the mysql data to volume. 

Let me know if that works :) 

For using a mysql container, for now you could set that up using the config files (also using a volume).   The init would start up mysql but it won't be used.  I'll look into implementing a mysql container but there are a few downsides to doing that for your monitoring system.   One being that anytime the mysql container is restarted  updated, etc you need to make sure to restart the icinga2 container.   Depending on your monitoring needs this could cause havoc :(

**Comment by jjethwa** [comment]
Hi @bscott 

I've made some modifications to the container logic.  If the /var/lib/mysql directory is empty when using an empty volume for example, the container now initializes the database correctly.  I've also the DATABASE_URL variable so you can supply an external MySQL container for example: jdbc:mysql://my_linked_mysql_database/rundeckdb?autoReconnect=true

Please let me know if this works for you :)

**Comment by jjethwa** [comment]
No response from user.  Marking as duplicate and closing as discussion and work is being detailed here: https://github.com/jjethwa/rundeck/issues/7
