### ISSUE TITLE
ENV variables defined wrong

### ISSUE THREAD

**Issue by sxmichael** [jjethwa/rundeck#61]
After https://github.com/jjethwa/rundeck/commit/9914f362e61f75810ac3215d01d47814f579dd08 ENV variables definition in Dockerfile was broken. ENV variable should be define one per line or use =. Currently docker produced have this output:
```
# env
HOSTNAME=8be484488a45
HOME=/root
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEBIAN_FRONTEND=noninteractive     SERVER_URL https://localhost:4443     RUNDECK_STORAGE_PROVIDER file     RUNDECK_PROJECT_STORAGE_TYPE file     NO_LOCAL_MYSQL false     LOGIN_MODULE RDpropertyfilelogin     JAAS_CONF_FILE jaas-loginmodule.conf     KEYSTORE_PASS adminadmin     TRUSTSTORE_PASS adminadmin
```
(a single DEBIAN_FRONTEND variable which contains all the long line)

**Comment by jjethwa** [comment]
Thanks so much for the issue and PR, @sxmichael   I had not noticed the problem before.  Really appreciate it 😃
