### ISSUE TITLE
Scheduling

### ISSUE THREAD

**Issue by elisalaborte** [jjethwa/rundeck#63]
Hi,

Besides the simple and cron scheduling, is it possible to schedule jobs based on other calendars like an accounting calendar for example?  I apologize, I know this isn't an issue but I don't know where to post this question. 

Thanks,
Elisa

**Comment by jjethwa** [comment]
Hi @elisalaborte 

Not that I know of unfortunately 😞   Might be worth putting in a feature request: https://github.com/rundeck/rundeck

**Comment by elisalaborte** [comment]
Thanks @jjethwa
