### ISSUE TITLE
cannot change -Dserver.web.context

### ISSUE THREAD

**Issue by phoenix086** [jjethwa/rundeck#64]
Hi,

according to docs it should be possible to set via RDECK_JVM the -Dserver.web.context.

docker run -p 4440:4440 -e SERVER_URL=http://localhost:4440 -e RDECK_JVM=-Dserver.web.context=/rundeck ...

This is not working for me. Rundeck gets still mapped to /

**Comment by jjethwa** [comment]
Hi @phoenix086 

Sorry about that.  There were some changes to the profile from 2.7 -> 2.8.  You'll need to use the RDECK_JVM_SETTINGS variable now.

So try 
```
-e RDECK_JVM_SETTINGS="-Xmx1024m -Xms256m -XX:MaxMetaspaceSize=256m -server -Dfile.encoding=UTF-8 -Dserver.web.context=/rundeck"

**Comment by phoenix086** [comment]
thank you for your effort - its working now, nice work all in all, appreciate it

**Comment by jjethwa** [comment]
That's great news, @phoenix086   Thanks for opening the issue.  I've updated the readme 😄
