### ISSUE TITLE
Release with jdk8u131 to enable -XX:+UseCGroupMemoryLimitForHeap

### ISSUE THREAD

**Issue by olvesh** [jjethwa/rundeck#66]
I would love to have these settings enabled:
``` -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1```

But it is only supported in [jdk8u131](https://dzone.com/articles/running-a-jvm-in-a-container-without-getting-kille)
The current release sports 8u121

**Comment by jjethwa** [comment]
Hi @olvesh 

Thanks for the issue.  I've updated the container 😄 

```
# java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```
