### ISSUE TITLE
Debian Jessie is no longer the stable release channel

### ISSUE THREAD

**Issue by johnseekins** [jjethwa/rundeck#68]
This isn't a huge problem, but packages like `python-boto3` (super useful with AWS) aren't available in jessie, but are available in the stable branch.

**Comment by jjethwa** [comment]
Hi @johnseekins 

I was planning on upgrading as part of the next Rundeck release.  If you need it sooner, let me know 😄

**Comment by johnseekins** [comment]
No big deal. Just making sure it's on the radar.

**Comment by jjethwa** [comment]
Hi @johnseekins 

The dev tag is now on stretch 😃

**Comment by jjethwa** [comment]
Hi @johnseekins 

latest is now on stretch.  Please note that I have not updated Rundeck to 2.8.3 yet due to one or two issues I'm keeping an eye on
