### ISSUE TITLE
Allow Brand HTML to be set via an environment variable

### ISSUE THREAD

**Issue by eugeneduvenage** [jjethwa/rundeck#73]
Hi,

When deploying many rundeck containers into an environment it is useful to set the brand html via the rundeck.gui.brand.html property to set a visual reminder of the rundeck target environment (in the rundeck-config.properties file).

I propose adding an environment variable GUI_BRAND_HTML which can set this property within the /opt/run script. I have working code in a branch at https://github.com/eugeneduvenage/rundeck/tree/set-brand-via-env which does the following:

* Checks if the GUI_BRAND_HTML variable is set.
* If iGUI_BRAND_HTML is set check if the property already exists in the file
* If  the property already exists in the file then use sed to replace with GUI_BRAND_HTML
* Else if the property does not exist in the file use echo to append to the file

If you are happy with the proposal I can submit a pull request.  

Regards,
Eugene Duvenage

**Comment by jjethwa** [comment]
Hi @eugeneduvenage 

Sounds great!  Please send a PR when you have time.  Does the HTML string need to be encapsulated by quotes?

**Comment by jjethwa** [comment]
Thanks for the PR @eugeneduvenage 

Just merged the PR.  It'll be in the latest version of the container on Docker Hub in a few minutes 😄
