### ISSUE TITLE
rundeck 2.9.1 released

### ISSUE THREAD

**Issue by chenlingmin** [jjethwa/rundeck#80]

**Comment by jjethwa** [comment]
Hi @chenlingmin 

Thanks for the issue and PR.  I'll review in a few minutes 😄

**Comment by jjethwa** [comment]
Closed: https://github.com/jjethwa/rundeck/pull/81

2.9.1 added: https://github.com/jjethwa/rundeck/commit/49ba776c198cd9bb8519c414a4c65fcb72d58e70

Building to latest now 😄
