### ISSUE TITLE
Allow for key storage in database

### ISSUE THREAD

**Issue by zleswomp** [jjethwa/rundeck#9]
Currently, when using an external database, keys are still stored on disk.  This proves to complicate when working in an environment where the underlying storage cannot be relied upon.  This comes up for us because we don't know what instance the container will start on, and there is not a way for us to share storage among instances.  Having the key storage in the database would likely assist in this.

It seems that rundeck is capable of this: http://rundeck.org/docs/administration/key-storage.html#storage-backends  and http://rundeck.org/docs/plugins-user-guide/configuring.html#storage-plugins

Is this something you can help with?

**Comment by jjethwa** [comment]
Hi @zleswomp 

Thanks for the issue :)  That's something we ran into earlier in our set up as well.  By default Rundeck writes keys to /var/lib/rundeck/var/storage  So for our use case, we use a (docker) volume when starting up the container: -v /<my_mount>/rundeck/var/lib/rundeck/var/storage:/var/lib/rundeck/var/storage  

I'm assuming you use a volume for your /etc/rundeck configs, right?  If so, you can override the rundeck-config.properties (or rundeck-config.groovy) with the settings to use the db for storage if you don't want to use the file method.

We prefer using files for as much as we can as they are easier to work with and if the database ever has a problem, the worst case is we lose the historical data but we can easily bring up a new rundeck instance with a fresh database and all necessary configs (/etc/rundeck), storage (/var/lib/rundeck/var/storage), project properties, (/var/rundeck), and jobs (exported to git and also exported to YAML on the file system).

Let me know if that helps :)

**Comment by zleswomp** [comment]
I'm not currently using a volume for configuration.  The reason is that it does me little good right now due to the way we are using docker.  If we restart the container for rundeck, we don't know which actual instance in the cluster the container will come up on, and to create a volume would be tied to a specific instance without any syncing across instances.  I hear you about using configuration files, but that would require more modification of our environment than I was hoping for.  Without a guarantee of local storage, using this image may prove challenging for us.  So, as much as possible, I'd like to be able to pass in environment variables to perform the necessary tweaks so I don't have to rely on local storage.

**Comment by jjethwa** [comment]
Hi @zleswomp 

Ah, got it.  I think I have a good idea about your use case now.  I can add a new variable for the storage provider (file or db) then have the initscript (/opt/run) modify the /etc/rundeck/rundeck-config.properties file.  Give me a bit :)

**Comment by jjethwa** [comment]
Hi @zleswomp 

I've tested (locally) and committed it: https://github.com/jjethwa/rundeck/commit/30bd9892ee0dc249fdfe77fe26c29c57305f3c85

Please pull the latest image from Docker HUb (or build it yourself with the latest changes from git) and start a container with the new variable `-e RUNDECK_STORAGE_PROVIDER=db`

**Comment by zleswomp** [comment]
Thank you for the quick response.  I've set the `RUNDECK_STORAGE_PROVIDER` variable to 'db', but I stil see /var/lib/rundeck/.ssh/id_rsa created locally.  I've connected to the database from within the container manually to poke around, and it seems that the project is also not getting created in the external database, despite having `DATABASE_URL` configured.  Looking in `/var/rundeck/projects/`, I do see the project gets created there, so it seems that I'm either doing something incorrectly, or using an external database isn't working for us.  Any idea why that might be?

**Comment by jjethwa** [comment]
Hi @zleswomp 

/var/lib/rundeck/.ssh/id_rsa is generated automatically at container startup, but you don't need to use it.  In the project configuration section: http://rundeck.org/2.6.4/manual/configure.html#project-configuration  you can specify a key to be used for SSH from storage.

For the external database, have you followed the section on setting up the database: http://rundeck.org/docs/administration/setting-up-an-rdb-datasource.html ?

**Comment by zleswomp** [comment]
Hi, Since the `DATABASE_URL` is passed into the environment, it looks like this image adds the necessary configuration to connect to the database into the `rundeck-config.properties` file.  I see the table structure in place in our external database, but it contains no data even after creating a project.  And specifically, if I stop the container and start a new one with the same settings, the projects I created are not present, which is unexpected.  My expectation is that when setting the `DATABASE_URL` and creating a project, that the project will be present when the running instance of the container is stopped and a new one is created.

**Comment by zleswomp** [comment]
Okay, so I created a password after following the documentation you linked, and I do see it listen in the `storage` table of the database.  So the connection is working at least.  Connecting to the database manually I run `select * from scheduled_execution;` which shows a project execution that I expect, but the project information itself is not stored in the `project` table.  I don't know if this is expected.  I see from http://rundeck.org/docs/plugins-user-guide/configuring.html#storage-plugins that the default storage for the project data is the database, but I still see my `testing` project listed under the `/var/rundeck/projects/` directory.

**Comment by jjethwa** [comment]
Hmm, it looks like it may still be creating project related configs under /var/rundeck/projects

Can you try docker exec'ing into the container, updating /etc/rundeck/rundeck-config.properties with

`rundeck.projectsStorageType=db`

then restarting rundeck via a supervisotctl stop rundeck && supervisorctl start rundeck

If that works, I can add that as a variable as well.  Thanks :)

**Comment by zleswomp** [comment]
That seems to have worked.  Running `select * from project;` shows my single test project listed there.  I still see `/var/rundeck/projects/tests/etc/project.properties` gets created for the `tests` project, but I'm not certain the impact if that file is not present when the container comes up without it.  Hopefully that information is pulled from the database.

**Comment by jjethwa** [comment]
Thanks, @zleswomp 

Please try pulling the latest container and adding `-e RUNDECK_PROJECT_STORAGE_TYPE=db`

**Comment by zleswomp** [comment]
Whoa. Nelly.  I think its working.  Still confirming.

**Comment by jjethwa** [comment]
Thanks, @zleswomp 

That's great news and glad I could help.  I'll work on adding a way to disable MySQL as per your suggestion.  I'll go ahead and close this issue out, but feel free to re-open or create new issues as needed.  Appreciate it :)

**Comment by akhilesh0** [comment]
What is the parameter needs to be set in rundeck-config.properties to save password in DB instead of file ?

**Comment by jjethwa** [comment]
Hi @akhilesh0 

Typically you create new issues for this sort of thing instead of commandeering someone else's. If you're talking about Rundeck key storage, you would set the RUNDECK_STORAGE_PROVIDER environment variable to dB.
