### ISSUE TITLE
rundeck.gui.brand.html GUI Customization

### ISSUE THREAD

**Issue by RenTamu** [jjethwa/rundeck#92]
Could you help me to make custom Brand Title.

I added below in /etc/rundeck/profile
---
GUI_BRAND_HTML='<span class="title">QA Environment</span>'
---

What about rundeck.gui.brand.html and rundeck-config.properties ? What needs to be done.?

Thanks

**Comment by jjethwa** [comment]
Hi @RenTamu 

Sorry for the delay, I was on vacation 😄 

Actually, you should set the environment variable as part of your docker run arguments so something like:
```
-e GUI_BRAND_HTML='QA Environment'
```

This will allow the container run script to do it's thing: https://github.com/jjethwa/rundeck/blob/master/content/opt/run#L156-L163

**Comment by RenTamu** [comment]
@jjethwa  Thanks ! 👍 
Also is it posible to have custom logo instead of rundeck in the title header if posible please let me know.

**Comment by jjethwa** [comment]
Hi @RenTamu 

NP!  Here's a full list of the GUI Customizations for Rundeck: http://rundeck.org/docs/administration/gui-customization.html

You can make your customization to the rundeck-config.properties file and you should be good to go 😄

**Comment by RenTamu** [comment]
Thanks @jjethwa ..!
Closing this ticket as resolved.
