### ISSUE TITLE
$RDECK_JVM_OPTS used, but not documented?

### ISSUE THREAD

**Issue by lavahot** [jjethwa/rundeck#98]
https://github.com/jjethwa/rundeck/blob/8a2134e98184a754cc8730c613a9fc7c62b8ec7c/content/opt/rundeck-defaults/profile#L65

This is the only place this variable is mentioned in the entire repository. Why is it here? Shouldn't it be removed due to the introduction of $RDECK_JVM_SETTINGS?

**Comment by jjethwa** [comment]
Hi @lavahot 

You're correct, it's better to use RDECK_JVM_SETTINGS now.  RDECK_JVM_OPTS is only around for backward compatibility 😄
